language: c++
compiler: g++
dist: focal

before_install:
  - sudo apt-get update -y && export DEBIAN_FRONTEND=noninteractive

install:
  - sudo apt-get install -y cmake
  - sudo apt-get -y install --no-install-recommends libboost-all-dev libopencv-dev

script:
  - mkdir build
  - cmake --preset boltzmann-makefiles-configure -B build -S .
  - make
  - make test